"""HTML report (spec section 6/94). This produces a single self-contained
static HTML *file* for sharing/archiving -- it is explicitly not, and must
never become, the primary interface to SlopScan. It reuses the Markdown
renderer's structure rather than duplicating layout logic, then wraps it in
minimal, dependency-free styling."""

from __future__ import annotations

import html as html_lib

from slopscan.core.models import ScanResult, Severity

_SEVERITY_CLASS = {
    Severity.LOW: "low",
    Severity.MEDIUM: "med",
    Severity.HIGH: "high",
    Severity.CRITICAL: "crit",
}

_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SlopScan report -- {target}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, "Segoe UI", Helvetica, Arial, sans-serif; max-width: 880px;
          margin: 3rem auto; padding: 0 1.5rem; line-height: 1.55; color: #1a1a1a; background: #fff; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  .target {{ color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; word-break: break-all; }}
  .scores {{ display: flex; gap: 2rem; margin: 1.5rem 0; }}
  .score-box {{ border: 1px solid #ddd; border-radius: 6px; padding: 1rem 1.5rem; }}
  .score-box .value {{ font-size: 2rem; font-weight: 600; }}
  .score-box .label {{ font-size: 0.8rem; color: #666; text-transform: uppercase; letter-spacing: 0.04em; }}
  .disclaimer {{ background: #f6f6f6; border-left: 3px solid #999; padding: 0.75rem 1rem; font-size: 0.9rem; margin: 1.5rem 0; }}
  table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
  th, td {{ text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #eee; }}
  .finding {{ border: 1px solid #eee; border-radius: 6px; padding: 1rem; margin-bottom: 0.75rem; }}
  .badge {{ display: inline-block; font-size: 0.7rem; font-weight: 700; padding: 0.1rem 0.5rem;
            border-radius: 3px; margin-right: 0.5rem; letter-spacing: 0.03em; }}
  .badge.low {{ background: #eef; color: #337; }}
  .badge.med {{ background: #fef3d5; color: #8a6100; }}
  .badge.high {{ background: #fde2e1; color: #942; }}
  .badge.crit {{ background: #331; color: #fff; }}
  ul {{ margin: 0.5rem 0; padding-left: 1.3rem; }}
  footer {{ margin-top: 2.5rem; font-size: 0.8rem; color: #888; border-top: 1px solid #eee; padding-top: 1rem; }}
</style>
</head>
<body>
<h1>SlopScan report</h1>
<div class="target">{target}</div>

<div class="scores">
  <div class="score-box"><div class="value">{score:.0f}%</div><div class="label">AI-slop likelihood</div></div>
  <div class="score-box"><div class="value">{confidence:.0f}%</div><div class="label">Confidence</div></div>
</div>

<div class="disclaimer">
  This score measures the presence of patterns statistically associated with AI-generated or
  generic template-driven work. It does <strong>not</strong> prove AI authorship.
</div>

<h2>Breakdown</h2>
<table><thead><tr><th>Category</th><th>Score</th></tr></thead><tbody>
{category_rows}
</tbody></table>

<h2>Top findings</h2>
{findings_html}

{positive_html}
{ai_html}
{warnings_html}

<footer>
  Scanned {files_scanned} file(s), evaluated {rules_evaluated} rules in {duration:.2f}s.
  Generated by SlopScan {version}.
</footer>
</body>
</html>
"""


def _esc(s: str) -> str:
    return html_lib.escape(s, quote=True)


def render_html(result: ScanResult) -> str:
    category_rows = "\n".join(
        f"<tr><td>{_esc(c.category.value.replace('_', ' ').title())}</td><td>{c.score:.0f}%</td></tr>"
        for c in result.categories
        if not (c.weight == 0 and c.finding_count == 0)
    )

    findings_html_parts = []
    for f in result.top_findings(limit=12):
        ev_items = "".join(
            f"<li>{_esc(e.description)}"
            + (f" <code>{_esc(e.locator)}</code>" if e.locator else "")
            + "</li>"
            for e in f.evidence[:6]
        )
        findings_html_parts.append(
            f'<div class="finding"><span class="badge {_SEVERITY_CLASS[f.severity]}">'
            f"{f.severity.value.upper()}</span><strong>{_esc(f.title)}</strong>"
            f"<p>{_esc(f.description)}</p><ul>{ev_items}</ul></div>"
        )
    findings_html = "\n".join(findings_html_parts) or "<p>No significant findings.</p>"

    positive_html = ""
    if result.positive_signals:
        items = "".join(f"<li>{_esc(p.description)}</li>" for p in result.positive_signals)
        positive_html = f"<h2>Positive signals</h2><ul>{items}</ul>"

    ai_html = ""
    if result.ai_interpretation:
        ai = result.ai_interpretation
        obs = "".join(f"<li>{_esc(o)}</li>" for o in ai.notable_observations)
        ai_html = (
            f"<h2>AI-assisted interpretation ({_esc(ai.provider)}/{_esc(ai.model)})</h2>"
            f"<p><em>Probabilistic interpretation of the deterministic evidence above; "
            f"never overrides it.</em></p><p>{_esc(ai.summary)}</p><ul>{obs}</ul>"
        )

    warnings_html = ""
    if result.warnings:
        items = "".join(f"<li>{_esc(w)}</li>" for w in result.warnings)
        warnings_html = f"<h2>Warnings</h2><ul>{items}</ul>"

    return _TEMPLATE.format(
        target=_esc(result.target),
        score=result.slop_score,
        confidence=result.confidence,
        category_rows=category_rows,
        findings_html=findings_html,
        positive_html=positive_html,
        ai_html=ai_html,
        warnings_html=warnings_html,
        files_scanned=result.stats.files_scanned,
        rules_evaluated=result.stats.rules_evaluated,
        duration=result.stats.duration_seconds,
        version=result.slopscan_version,
    )
