"""Markdown report (spec section 6). Suitable for pasting into a PR
description or a CI job summary."""

from __future__ import annotations

from slopscan.core.models import ScanResult, Severity

_SEVERITY_LABEL = {
    Severity.LOW: "LOW",
    Severity.MEDIUM: "MED",
    Severity.HIGH: "HIGH",
    Severity.CRITICAL: "CRIT",
}


def render_markdown(result: ScanResult) -> str:
    lines: list[str] = []
    lines.append(f"# SlopScan report -- {result.target}")
    lines.append("")
    lines.append(f"**AI-Slop likelihood:** {result.slop_score:.0f}%  ")
    lines.append(f"**Confidence:** {result.confidence:.0f}%")
    lines.append("")
    lines.append(
        "> This score measures the presence of patterns statistically associated with "
        "AI-generated or generic template-driven work. It does not prove AI authorship."
    )
    lines.append("")

    lines.append("## Breakdown")
    lines.append("")
    lines.append("| Category | Score |")
    lines.append("|---|---|")
    for c in result.categories:
        if c.weight == 0 and c.finding_count == 0:
            continue
        label = c.category.value.replace("_", " ").title()
        lines.append(f"| {label} | {c.score:.0f}% |")
    lines.append("")

    top = result.top_findings(limit=10)
    if top:
        lines.append("## Top findings")
        lines.append("")
        for f in top:
            lines.append(f"### `{_SEVERITY_LABEL[f.severity]}` {f.title}")
            lines.append("")
            lines.append(f.description)
            lines.append("")
            for e in f.evidence[:5]:
                loc = f" (`{e.locator}`)" if e.locator else ""
                lines.append(f"- {e.description}{loc}")
            lines.append("")

    if result.positive_signals:
        lines.append("## Positive signals")
        lines.append("")
        for p in result.positive_signals:
            lines.append(f"- {p.description}")
        lines.append("")

    if result.ai_interpretation:
        ai = result.ai_interpretation
        lines.append(f"## AI-assisted interpretation ({ai.provider}/{ai.model})")
        lines.append("")
        lines.append(
            "*This section is a probabilistic interpretation of the deterministic evidence above, "
            "generated by an external model. It never overrides the deterministic findings.*"
        )
        lines.append("")
        lines.append(ai.summary)
        if ai.notable_observations:
            lines.append("")
            for obs in ai.notable_observations:
                lines.append(f"- {obs}")
        if ai.caveats:
            lines.append("")
            lines.append("**Caveats:**")
            for caveat in ai.caveats:
                lines.append(f"- {caveat}")
        lines.append("")

    if result.warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in result.warnings:
            lines.append(f"- {w}")
        lines.append("")

    lines.append("---")
    lines.append(
        f"Scanned {result.stats.files_scanned} file(s), evaluated {result.stats.rules_evaluated} rules "
        f"in {result.stats.duration_seconds:.2f}s. Generated by SlopScan {result.slopscan_version}."
    )
    return "\n".join(lines)
